<a href="https://colab.research.google.com/github/devyani-nandankar/devyani-nandankar.ML-practical.io/blob/main/ML_LAB_PRACTICAL_NO_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Devyani Nandankar(CS23018)

ML LAB-5 AIM: To build and evaluate a Decision Tree model for classification tasks and study the effect of tree depth and splitting criteria.

In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path= '/content/drive/MyDrive/ML_DATASET/daily_weather.csv'
df=pd.read_csv(path)
df.head(5)

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.0,0.0,42.420000,36.160000
1,1,917.347688,71.403843,101.935179,2.443009,140.471549,3.533324,0.0,0.0,24.328697,19.426597
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.0,20.0,8.900000,14.460000
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.0,0.0,12.189102,12.742547
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.9,14730.0,92.410000,76.740000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   number                  1095 non-null   int64
 1   air_pressure_9am        1092 non-null   float64
 2   air_temp_9am            1090 non-null   float64
 3   avg_wind_direction_9am  1091 non-null   float64
 4   avg_wind_speed_9am      1092 non-null   float64
 5   max_wind_direction_9am  1092 non-null   float64
 6   max_wind_speed_9am      1091 non-null   float64
 7   rain_accumulation_9am   1089 non-null   float64
 8   rain_duration_9am       1092 non-null   float64
 9   relative_humidity_9am   1095 non-null   float64
 10  relative_humidity_3pm   1095 non-null   float64
dtypes: float64(10), int64(1)
memory usage: 94.2 KB

In [ ]:
df.head()

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
0,0,918.060000,74.822000,271.100000,2.080354,295.400000,2.863283,0.0,0.0,42.420000,36.160000
1,1,917.347688,71.403843,101.935179,2.443009,140.471549,3.533324,0.0,0.0,24.328697,19.426597
2,2,923.040000,60.638000,51.000000,17.067852,63.700000,22.100967,0.0,20.0,8.900000,14.460000
3,3,920.502751,70.138895,198.832133,4.337363,211.203341,5.190045,0.0,0.0,12.189102,12.742547
4,4,921.160000,44.294000,277.800000,1.856660,136.500000,2.863283,8.9,14730.0,92.410000,76.740000

In [ ]:
print(df)

      number  air_pressure_9am  air_temp_9am  avg_wind_direction_9am  \
0          0        918.060000     74.822000              271.100000
1          1        917.347688     71.403843              101.935179
2          2        923.040000     60.638000               51.000000
3          3        920.502751     70.138895              198.832133
4          4        921.160000     44.294000              277.800000
...      ...               ...           ...                     ...
1090    1090        918.900000     63.104000              192.900000
1091    1091        918.710000     49.568000              241.600000
1092    1092        916.600000     71.096000              189.300000
1093    1093        912.600000     58.406000              172.700000
1094    1094        921.530000     77.702000               97.100000

      avg_wind_speed_9am  max_wind_direction_9am  max_wind_speed_9am  \
0               2.080354              295.400000            2.863283
1               2.443009              140.471549            3.533324
2              17.067852               63.700000           22.100967
3               4.337363              211.203341            5.190045
4               1.856660              136.500000            2.863283
...                  ...                     ...                 ...
1090            3.869906              207.300000            5.212070
1091            1.811921              227.400000            2.371156
1092            3.064608              200.800000            3.892276
1093            3.825167              189.100000            4.764682
1094            3.265932              125.900000            4.451511

      rain_accumulation_9am  rain_duration_9am  relative_humidity_9am  \
0                       0.0                0.0              42.420000
1                       0.0                0.0              24.328697
2                       0.0               20.0               8.900000
3                       0.0                0.0              12.189102
4                       8.9            14730.0              92.410000
...                     ...                ...                    ...
1090                    0.0                0.0              26.020000
1091                    0.0                0.0              90.350000
1092                    0.0                0.0              45.590000
1093                    0.0                0.0              64.840000
1094                    0.0                0.0              14.560000

      relative_humidity_3pm
0                 36.160000
1                 19.426597
2                 14.460000
3                 12.742547
4                 76.740000
...                     ...
1090              38.180000
1091              73.340000
1092              52.310000
1093              58.280000
1094              15.100000

[1095 rows x 11 columns]

In [ ]:
df.shape

(1095, 11)

In [ ]:
df.describe()

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
count,1095.000000,1092.000000,1090.000000,1091.000000,1092.000000,1092.000000,1091.000000,1089.000000,1092.000000,1095.000000,1095.000000
mean,547.000000,918.882551,64.933001,142.235511,5.508284,148.953518,7.019514,0.203079,294.108052,34.241402,35.344727
std,316.243577,3.184161,11.175514,69.137859,4.552813,67.238013,5.598209,1.593952,1598.078779,25.472067,22.524079
min,0.000000,907.990000,36.752000,15.500000,0.693451,28.900000,1.185578,0.000000,0.000000,6.090000,5.300000
25%,273.500000,916.550000,57.281000,65.972506,2.248768,76.553003,3.067477,0.000000,0.000000,15.092243,17.395000
50%,547.000000,918.921045,65.715479,166.000000,3.871333,177.300000,4.943637,0.000000,0.000000,23.179259,24.380000
75%,820.500000,921.160073,73.450974,191.000000,7.337163,201.233153,8.947760,0.000000,0.000000,45.400000,52.060000
max,1094.000000,929.320000,98.906000,343.400000,23.554978,312.200000,29.840780,24.020000,17704.000000,92.620000,92.250000

In [ ]:
df.columns

Index(['number', 'air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am', 'relative_humidity_9am',
       'relative_humidity_3pm'],
      dtype='object')

In [ ]:
#Data Cleaning: Output "True" --> means that there are some null values
df.isnull().any().any()

np.True_

In [ ]:
df.isnull().sum()

number                    0
air_pressure_9am          3
air_temp_9am              5
avg_wind_direction_9am    4
avg_wind_speed_9am        3
max_wind_direction_9am    3
max_wind_speed_9am        4
rain_accumulation_9am     6
rain_duration_9am         3
relative_humidity_9am     0
relative_humidity_3pm     0
dtype: int64

In [ ]:
#Print the rows with missing values.
df[df.isnull().any(axis = 1)]

,number,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am,relative_humidity_9am,relative_humidity_3pm
16,16,917.890000,NaN,169.200000,2.192201,196.800000,2.930391,0.000,0.000000,48.990000,51.190000
111,111,915.290000,58.820000,182.600000,15.613841,189.000000,NaN,0.000,0.000000,21.500000,29.690000
177,177,915.900000,NaN,183.300000,4.719943,189.900000,5.346287,0.000,0.000000,29.260000,46.500000
262,262,923.596607,58.380598,47.737753,10.636273,67.145843,13.671423,0.000,NaN,17.990876,16.461685
277,277,920.480000,62.600000,194.400000,2.751436,NaN,3.869906,0.000,0.000000,52.580000,54.030000
334,334,916.230000,75.740000,149.100000,2.751436,187.500000,4.183078,NaN,1480.000000,31.880000,32.900000
358,358,917.440000,58.514000,55.100000,10.021491,NaN,12.705819,0.000,0.000000,13.880000,25.930000
361,361,920.444946,65.801845,49.823346,21.520177,61.886944,25.549112,NaN,40.364018,12.278715,7.618649
381,381,918.480000,66.542000,90.900000,3.467257,89.400000,4.406772,NaN,0.000000,20.640000,14.350000
409,409,NaN,67.853833,65.880616,4.328594,78.570923,5.216734,0.000,0.000000,18.487385,20.356594
517,517,920.570000,53.600000,100.100000,4.697574,NaN,6.285801,4.712,14842.000000,79.880000,84.530000
519,519,916.250000,55.670000,176.400000,6.666081,188.200000,NaN,0.000,0.000000,72.550000,74.390000
546,546,NaN,42.746000,251.100000,12.929513,274.400000,17.604718,14.627,7825.000000,87.870000,70.770000
620,620,921.200000,56.786000,192.300000,9.551734,201.400000,11.005745,NaN,0.000000,59.790000,77.750000
625,625,912.400000,50.774000,171.600000,NaN,181.400000,4.831790,0.000,0.000000,86.840000,64.740000
656,656,920.830000,66.344000,NaN,15.457255,189.400000,16.486248,0.000,0.000000,23.770000,51.630000
670,670,910.920000,48.362000,156.500000,NaN,177.500000,16.128337,4.970,10560.000000,80.560000,88.220000
672,672,922.448945,72.863773,NaN,3.682370,214.196160,4.849450,0.000,0.000000,16.753670,17.804720
705,705,911.900000,59.072000,199.800000,1.275056,239.500000,1.834291,NaN,0.000000,77.630000,59.130000
731,731,922.970167,51.391847,33.810942,NaN,59.290089,11.111555,0.000,4.735034,34.807753,18.418179
737,737,917.895130,76.804690,104.771020,1.632705,97.178763,NaN,0.000,0.000000,13.771311,16.792455
788,788,917.923442,73.249717,42.101739,4.132698,64.284969,5.345258,0.000,NaN,6.939692,18.793825
840,840,918.043767,NaN,181.774042,0.964376,185.618601,1.570007,0.000,0.000000,11.911222,18.154358
848,848,915.250000,37.562000,246.500000,11.587349,258.700000,NaN,3.171,2891.000000,91.000000,90.780000
861,861,919.065408,NaN,172.303728,2.639600,193.058141,3.326949,0.000,0.000000,12.497839,13.438518
869,869,NaN,45.104000,259.000000,3.265932,275.000000,4.026492,0.000,80.000000,85.270000,90.260000
998,998,914.140000,71.240000,NaN,1.722444,232.900000,2.326418,0.000,0.000000,24.200000,41.380000
1031,1031,922.669195,NaN,47.946284,7.969686,65.770066,10.262337,0.000,0.000000,18.920805,19.641841
1035,1035,919.670000,77.576000,171.800000,6.554234,191.000000,8.164831,0.000,NaN,56.860000,50.650000
1063,1063,917.300185,65.790001,NaN,1.879553,222.498226,2.692862,0.000,0.000000,14.972668,20.966267
1066,1066,919.564869,73.726732,68.704694,3.551777,102.571616,4.861315,NaN,0.000000,11.657314,17.331823

In [ ]:
#We do not need to number the rows as Pandas provides it's own indexing.
del df['number']
df.columns

Index(['air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am', 'relative_humidity_9am',
       'relative_humidity_3pm'],
      dtype='object')

In [ ]:
df.shape

(1095, 10)

In [ ]:
before_rows = df.shape[0]
df = df.dropna()
after_rows = df.shape[0]

print("Before rows: ", before_rows)
print("After rows: ", after_rows)
print("The number of dropped rows are: ", before_rows - after_rows)
#print("The number of dropped rows are ()".format(before_rows - after_rows))

Before rows:  1095
After rows:  1064
The number of dropped rows are:  31

In [ ]:
df.shape

(1064, 10)

In [ ]:

clean_data=df.copy()
clean_data['high_humidity_label']=(clean_data['relative_humidity_3pm']>24.99)*1
print(clean_data['high_humidity_label'])

0       1
1       0
2       0
3       0
4       1
       ..
1090    1
1091    1
1092    1
1093    1
1094    0
Name: high_humidity_label, Length: 1064, dtype: int64

In [ ]:
clean_data.columns

Index(['air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am', 'relative_humidity_9am',
       'relative_humidity_3pm', 'high_humidity_label'],
      dtype='object')

In [ ]:
clean_data.shape

(1064, 11)

In [ ]:
#We do not need to 'relative humidity 9am' and 'relative humidity 3pm'the rows
del clean_data['relative_humidity_9am']
del clean_data['relative_humidity_3pm']
clean_data.columns

Index(['air_pressure_9am', 'air_temp_9am', 'avg_wind_direction_9am',
       'avg_wind_speed_9am', 'max_wind_direction_9am', 'max_wind_speed_9am',
       'rain_accumulation_9am', 'rain_duration_9am', 'high_humidity_label'],
      dtype='object')

In [ ]:
clean_data.shape

(1064, 9)

In [ ]:
##Split dataset into independent and dependant features.
X=clean_data.iloc[:,:-1]
print(X)

      air_pressure_9am  air_temp_9am  avg_wind_direction_9am  \
0           918.060000     74.822000              271.100000
1           917.347688     71.403843              101.935179
2           923.040000     60.638000               51.000000
3           920.502751     70.138895              198.832133
4           921.160000     44.294000              277.800000
...                ...           ...                     ...
1090        918.900000     63.104000              192.900000
1091        918.710000     49.568000              241.600000
1092        916.600000     71.096000              189.300000
1093        912.600000     58.406000              172.700000
1094        921.530000     77.702000               97.100000

      avg_wind_speed_9am  max_wind_direction_9am  max_wind_speed_9am  \
0               2.080354              295.400000            2.863283
1               2.443009              140.471549            3.533324
2              17.067852               63.700000           22.100967
3               4.337363              211.203341            5.190045
4               1.856660              136.500000            2.863283
...                  ...                     ...                 ...
1090            3.869906              207.300000            5.212070
1091            1.811921              227.400000            2.371156
1092            3.064608              200.800000            3.892276
1093            3.825167              189.100000            4.764682
1094            3.265932              125.900000            4.451511

      rain_accumulation_9am  rain_duration_9am
0                       0.0                0.0
1                       0.0                0.0
2                       0.0               20.0
3                       0.0                0.0
4                       8.9            14730.0
...                     ...                ...
1090                    0.0                0.0
1091                    0.0                0.0
1092                    0.0                0.0
1093                    0.0                0.0
1094                    0.0                0.0

[1064 rows x 8 columns]

In [ ]:
y=clean_data.iloc[:,-1]
print(y)

0       1
1       0
2       0
3       0
4       1
       ..
1090    1
1091    1
1092    1
1093    1
1094    0
Name: high_humidity_label, Length: 1064, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, test_size = 0.3, random_state = 42)

In [ ]:
X_test

,air_pressure_9am,air_temp_9am,avg_wind_direction_9am,avg_wind_speed_9am,max_wind_direction_9am,max_wind_speed_9am,rain_accumulation_9am,rain_duration_9am
32,918.700000,76.226000,184.600000,4.093600,194.900000,4.742313,0.0,0.0
1084,917.130000,80.240000,183.300000,1.632966,38.500000,2.259309,0.0,0.0
423,921.090000,70.124000,182.800000,2.908022,204.500000,3.534365,0.0,0.0
767,915.220000,73.292000,148.300000,1.789552,198.500000,2.908022,0.0,0.0
818,921.400000,63.050000,223.200000,1.319795,185.000000,1.879030,0.0,0.0
...,...,...,...,...,...,...,...,...
503,919.738161,67.432744,147.470881,1.157775,129.981819,1.899000,0.0,0.0
585,916.250000,79.754000,48.600000,1.073731,99.800000,1.588227,0.0,0.0
389,916.500000,74.588000,101.200000,1.834291,132.400000,2.594850,0.0,0.0
715,923.600000,65.030000,62.300000,7.091100,75.100000,8.410894,0.0,0.0
352,925.280000,66.470000,49.400000,11.229439,77.900000,15.345408,0.0,0.0